import type { Quiz } from '@ryzzquizz/shared';
import { funQuiz, qi } from './build.js';

// កម្សាន្ត · កីឡា · វប្បធម៌ខ្មែរ · ចំណេះដឹងទូទៅ — the lighter shelves.
// Every question carries a themed icon (safe, zero-asset) so these read as
// visual trivia slides rather than a wall of text, same as the guess quizzes.

export const FUN_QUIZZES: Quiz[] = [
  funQuiz('sports', 'កីឡា', 'Sports & Football', 'sports', '⚽', [
    qi('How many players from one team are on the pitch in football?', '⚽', ['9', '10', '11', '12'], 2),
    qi('Which country won the 2022 FIFA World Cup?', '🏆', ['France', 'Brazil', 'Argentina', 'Germany'], 2),
    qi('Which club is nicknamed "The Red Devils"?', '⚽', ['Liverpool', 'Manchester United', 'Arsenal', 'Chelsea'], 1),
    qi('How often are the Summer Olympic Games held?', '🏅', ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], 2),
    qi('In which sport would you perform a "slam dunk"?', '🏀', ['Volleyball', 'Basketball', 'Tennis', 'Badminton'], 1),
    qi('Which multi-sport games did Cambodia host in 2023?', '🥇', ['Asian Games', 'SEA Games', 'Olympic Games', 'Commonwealth Games'], 1),
    qi('Which traditional Cambodian martial art is contested at the SEA Games?', '🥋', ['Kun Khmer', 'Judo', 'Karate', 'Taekwondo'], 0),
    qi('How many points is a touchdown worth in American football?', '🏈', ['3', '6', '7', '10'], 1),
    qi('How many players are on a volleyball team on court?', '🏐', ['5', '6', '7', '11'], 1),
    qi('In tennis, what is a score of zero called?', '🎾', ['Nil', 'Love', 'Duck', 'Blank'], 1),
    qi('Which country has won the most FIFA World Cups?', '🏆', ['Germany', 'Italy', 'Brazil', 'Argentina'], 2),
    qi('How long is a standard football match (excluding stoppage)?', '⏱️', ['60 minutes', '80 minutes', '90 minutes', '120 minutes'], 2),
    qi('In which sport is the Tour de France contested?', '🚴', ['Running', 'Cycling', 'Swimming', 'Rowing'], 1),
    qi('How many rings are on the Olympic flag?', '🏅', ['3', '4', '5', '6'], 2),
    qi('Which sport uses a shuttlecock?', '🏸', ['Table tennis', 'Squash', 'Badminton', 'Cricket'], 2),
    qi('Which country is the origin of Taekwondo?', '🥋', ['Japan', 'China', 'South Korea', 'Vietnam'], 2),
    qi('In basketball, how many points is a shot from beyond the arc?', '🏀', ['1', '2', '3', '4'], 2),
    qi('What is the national sport most watched in Cambodia?', '⚽', ['Ice hockey', 'Football', 'Rugby', 'Golf'], 1),
  ], 18, 'easy'),

  funQuiz('movies', 'ភាពយន្ត និងរឿងភាគ', 'Movies & Series', 'entertainment', '🎬', [
    qi('Which film won Best Picture at the 2020 Academy Awards?', '🏆', ['Parasite', '1917', 'Joker', 'Roma'], 0),
    qi('In "The Lion King", what is the young lion\'s name?', '🦁', ['Mufasa', 'Simba', 'Scar', 'Nala'], 1),
    qi('Which series features a place called the "Upside Down"?', '📺', ['Dark', 'Stranger Things', 'The Witcher', 'Squid Game'], 1),
    qi('Who directed both "Titanic" and "Avatar"?', '🎬', ['Steven Spielberg', 'Christopher Nolan', 'James Cameron', 'Ridley Scott'], 2),
    qi('Which film series features a young wizard named Harry?', '⚡', ['The Hobbit', 'Harry Potter', 'Narnia', 'Percy Jackson'], 1),
    qi('"Squid Game" is a series from which country?', '📺', ['Japan', 'China', 'South Korea', 'Indonesia'], 2),
    qi('Which is the highest-grossing film of all time worldwide?', '🎬', ['Avatar', 'Avengers: Endgame', 'Titanic', 'Avatar: The Way of Water'], 0),
    qi('Which studio produced "Spirited Away"?', '🎨', ['Studio Ghibli', 'Pixar', 'DreamWorks', 'Walt Disney Animation'], 0),
    qi('Which superhero team appears in "The Avengers"?', '🦸', ['Justice League', 'X-Men', 'The Avengers', 'Fantastic Four'], 2),
    qi('Who directed "Inception" and "Interstellar"?', '🎬', ['Quentin Tarantino', 'Christopher Nolan', 'Martin Scorsese', 'Denis Villeneuve'], 1),
    qi('Which animated film features a snowman named Olaf?', '⛄', ['Moana', 'Frozen', 'Tangled', 'Encanto'], 1),
    qi('In "Star Wars", what is the name of Luke\'s father?', '🚀', ['Obi-Wan Kenobi', 'Han Solo', 'Darth Vader', 'Yoda'], 2),
    qi('Which streaming platform produced "Stranger Things"?', '📺', ['Disney+', 'Netflix', 'Amazon Prime', 'HBO'], 1),
    qi('Which country produces "Bollywood" films?', '🎬', ['Pakistan', 'India', 'Bangladesh', 'Nepal'], 1),
    qi('Which Cambodian director was nominated for an Academy Award?', '🎬', ['Rithy Panh', 'Davy Chou', 'Kulikar Sotho', 'Chhay Bora'], 0),
    qi('Which film features the quote "I\'ll be back"?', '🤖', ['Rocky', 'The Terminator', 'Rambo', 'Predator'], 1),
    qi('Which movie franchise features dinosaurs on an island?', '🦖', ['Jumanji', 'Jurassic Park', 'King Kong', 'Godzilla'], 1),
    qi('Which animated series features a yellow family from Springfield?', '📺', ['Family Guy', 'The Simpsons', 'South Park', 'Rick and Morty'], 1),
  ], 18, 'easy'),

  funQuiz('music', 'តន្ត្រី និង K-pop', 'Music & K-pop', 'entertainment', '🎵', [
    qi('How many members are in BTS?', '🎤', ['5', '6', '7', '8'], 2),
    qi('Which K-pop girl group released "How You Like That"?', '🎤', ['TWICE', 'BLACKPINK', 'Red Velvet', 'ITZY'], 1),
    qi('Which instrument has 88 keys?', '🎹', ['Guitar', 'Piano', 'Violin', 'Harp'], 1),
    qi('"Gangnam Style" was released by which artist?', '🎤', ['PSY', 'Rain', 'BIGBANG', 'G-Dragon'], 0),
    qi('Which traditional Cambodian instrument is a long-necked lute?', '🎸', ['Chapei Dong Veng', 'Roneat', 'Tro', 'Skor'], 0),
    qi('Which band recorded "Bohemian Rhapsody"?', '🎸', ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'], 1),
    qi('How many strings does a standard guitar have?', '🎸', ['4', '5', '6', '7'], 2),
    qi('Which music genre originated in Jamaica?', '🎵', ['Reggae', 'Jazz', 'Blues', 'Salsa'], 0),
    qi('Which K-pop group is known for "Kill This Love"?', '🎤', ['BLACKPINK', 'BTS', 'NCT', 'SEVENTEEN'], 0),
    qi('Which Cambodian percussion instrument is a barrel drum?', '🥁', ['Roneat', 'Skor', 'Tro', 'Khloy'], 1),
    qi('How many lines are on a standard musical staff?', '🎼', ['3', '4', '5', '6'], 2),
    qi('Which band released the album "Abbey Road"?', '🎸', ['The Rolling Stones', 'The Beatles', 'The Who', 'Pink Floyd'], 1),
    qi('Which term means "loud" in music notation?', '🎼', ['Piano', 'Forte', 'Adagio', 'Legato'], 1),
    qi('Which Cambodian xylophone-like instrument is played in pinpeat ensembles?', '🎼', ['Roneat', 'Chapei', 'Tro', 'Kong'], 0),
    qi('Which instrument family does the violin belong to?', '🎻', ['Strings', 'Brass', 'Woodwind', 'Percussion'], 0),
    qi('Which artist is known as the "Queen of Rock and Roll"?', '🎤', ['Tina Turner', 'Cher', 'Janis Joplin', 'Stevie Nicks'], 0),
    qi('Which K-pop agency manages BTS?', '🎤', ['SM Entertainment', 'HYBE (Big Hit)', 'YG Entertainment', 'JYP Entertainment'], 1),
    qi('What does "a cappella" mean?', '🎤', ['Singing without instruments', 'Very fast tempo', 'A type of drum', 'A duet'], 0),
  ], 18, 'medium'),

  funQuiz('anime-gaming', 'អានីមេ និងហ្គេម', 'Anime & Gaming', 'entertainment', '🎮', [
    qi('Which anime follows a ninja named Naruto Uzumaki?', '🥷', ['One Piece', 'Naruto', 'Bleach', 'Dragon Ball'], 1),
    qi('In Minecraft, which mob explodes when it gets close to you?', '💣', ['Creeper', 'Zombie', 'Skeleton', 'Enderman'], 0),
    qi('Which company created the PlayStation?', '🎮', ['Microsoft', 'Nintendo', 'Sony', 'Sega'], 2),
    qi('Who is the playable hero of "The Legend of Zelda"?', '🗡️', ['Zelda', 'Link', 'Ganon', 'Mario'], 1),
    qi('Which anime follows pirates searching for a treasure called "One Piece"?', '🏴‍☠️', ['Naruto', 'One Piece', 'Fairy Tail', 'Hunter x Hunter'], 1),
    qi('In Pokémon, what type is Pikachu?', '⚡', ['Fire', 'Water', 'Electric', 'Grass'], 2),
    qi('Which battle royale game announces "Victory Royale"?', '🎮', ['PUBG', 'Fortnite', 'Apex Legends', 'Free Fire'], 1),
    qi('Who directed "My Neighbor Totoro"?', '🎨', ['Hayao Miyazaki', 'Isao Takahata', 'Makoto Shinkai', 'Mamoru Hosoda'], 0),
    qi('Which company created Mario?', '🍄', ['Sega', 'Nintendo', 'Sony', 'Capcom'], 1),
    qi('In "Attack on Titan", what are the giant humanoids called?', '🗡️', ['Giants', 'Titans', 'Colossi', 'Ogres'], 1),
    qi('Which game features the character Kratos?', '⚔️', ['God of War', 'Halo', 'Doom', 'Gears of War'], 0),
    qi('Which anime film by Makoto Shinkai features body-swapping?', '🎨', ['Weathering With You', 'Your Name', 'Suzume', '5 Centimeters'], 1),
    qi('Which esports game is played 5v5 on Summoner\'s Rift?', '🎮', ['Dota 2', 'League of Legends', 'Valorant', 'Overwatch'], 1),
    qi('In Pokémon, who is the main rival organisation in the original games?', '⚡', ['Team Rocket', 'Team Aqua', 'Team Galactic', 'Team Flare'], 0),
    qi('Which console is made by Microsoft?', '🎮', ['PlayStation', 'Switch', 'Xbox', 'Dreamcast'], 2),
    qi('Which anime features the Straw Hat crew?', '🏴‍☠️', ['Bleach', 'One Piece', 'Naruto', 'Dragon Ball'], 1),
    qi('Which mobile game popular in Cambodia is a 5v5 MOBA?', '📱', ['Candy Crush', 'Mobile Legends', 'Subway Surfers', 'Temple Run'], 1),
    qi('What does "NPC" stand for in gaming?', '🎮', ['Non-Player Character', 'New Player Class', 'Next Playable Chapter', 'Network Play Console'], 0),
  ], 18, 'easy'),

  funQuiz('khmer-culture', 'វប្បធម៌ខ្មែរ', 'Khmer Culture & Traditions', 'culture', '🛕', [
    qi('របាំព្រះរាជទ្រព្យដ៏ល្បីល្បាញរបស់ខ្មែរឈ្មោះអ្វី?', '💃', ['របាំត្រុដិ', 'របាំអប្សរា', 'របាំកន្ទ្រឹម', 'របាំគោះអង្រែ'], 1),
    qi('ចាប៉ីដងវែងត្រូវបានចុះក្នុងបញ្ជីបេតិកភណ្ឌវប្បធម៌អរូបី UNESCO ក្នុងឆ្នាំណា?', '🎸', ['២០០៨', '២០១៦', '២០១៨', '២០២០'], 1),
    qi('បុណ្យអុំទូកប្រារព្ធធ្វើឡើងក្នុងខែណា?', '🚣', ['ខែមេសា', 'ខែវិច្ឆិកា', 'ខែកញ្ញា', 'ខែមករា'], 1),
    qi('បុណ្យភ្ជុំបិណ្ឌមានរយៈពេលប៉ុន្មានថ្ងៃ?', '🙏', ['៣ ថ្ងៃ', '៧ ថ្ងៃ', '១៥ ថ្ងៃ', '៣០ ថ្ងៃ'], 2),
    qi('ម្ហូបខ្មែរ «អាម៉ុក» ធ្វើពីសាច់អ្វីជាចម្បង?', '🍲', ['ត្រី', 'សាច់គោ', 'សាច់មាន់', 'បន្លែសុទ្ធ'], 0),
    qi('សំពត់បុរាណខ្មែរដែលត្បាញដោយសូត្រហៅថាអ្វី?', '🧵', ['សំពត់ហូល', 'ខោខ្លី', 'អាវយឺត', 'សំពត់ជីនស៍'], 0),
    qi('និកាយព្រះពុទ្ធសាសនាណាដែលជាសាសនាផ្លូវការនៅកម្ពុជា?', '🙏', ['មហាយាន', 'វជ្រយាន', 'ថេរវាទ', 'ព្រាហ្មណ៍'], 2),
    qi('សិល្បៈក្បាច់គុនបុរាណខ្មែរហៅថាអ្វី?', '🥋', ['បុកគាត់', 'ល្បុក្កតោ', 'ជូដូ', 'តៃក្វាន់ដូ'], 1),
    qi('បុណ្យចូលឆ្នាំខ្មែរមានរយៈពេលប៉ុន្មានថ្ងៃ?', '🎉', ['២ ថ្ងៃ', '៣ ថ្ងៃ', '៥ ថ្ងៃ', '៧ ថ្ងៃ'], 1),
    qi('ល្បែងប្រជាប្រិយខ្មែរដែលលេងក្នុងបុណ្យចូលឆ្នាំគឺអ្វី?', '🎯', ['ចោលឈូង', 'បាល់បោះ', 'អុកឆាំង', 'វាយសី'], 0),
    qi('«ព្រះខ័នរាជ» សំដៅលើអ្វី?', '⚔️', ['ដាវព្រះរាជទ្រព្យ', 'ប្រាសាទ', 'ភ្នំ', 'ទន្លេ'], 0),
    qi('សិល្បៈស្បែកធំ (ណាងស្បែក) ជាទម្រង់សិល្បៈអ្វី?', '🎭', ['ល្ខោនស្រមោលស្បែក', 'របាំបុរាណ', 'ចម្រៀង', 'គំនូរ'], 0),
    qi('ភេសជ្ជៈបុរាណខ្មែរដែលធ្វើពីទឹកត្នោតហៅថាអ្វី?', '🥥', ['ទឹកត្នោតជូរ', 'កាហ្វេ', 'តែ', 'ទឹកឃ្មុំ'], 0),
    qi('អាហារខ្មែរ «ប្រហុក» ធ្វើពីអ្វី?', '🐟', ['ត្រីប្រៃជ្រលក់', 'សាច់គោ', 'បន្លែស្រស់', 'អង្ករ'], 0),
    qi('ព្រះពុទ្ធសាសនាបានចូលមកកម្ពុជាតាមផ្លូវណា?', '🙏', ['ពាណិជ្ជកម្មពីឥណ្ឌា និងស្រីលង្កា', 'អឺរ៉ុប', 'អាមេរិក', 'អាហ្វ្រិក'], 0),
    qi('ឧបករណ៍តន្ត្រីខ្មែរដែលប្រើក្នុងក្រុមភ្លេងពិណពាទ្យរួមមានអ្វី?', '🎼', ['រនាត និងគង', 'ហ្គីតា', 'ព្យាណូ', 'ត្រុំបែត'], 0),
    qi('«បុណ្យកឋិន» ជាបុណ្យអ្វី?', '🙏', ['បុណ្យប្រគេនចីវរដល់ព្រះសង្ឃ', 'បុណ្យអុំទូក', 'បុណ្យចូលឆ្នាំ', 'បុណ្យបញ្ចុះខ្មោច'], 0),
    qi('ស្ថាបត្យកម្មប្រាសាទខ្មែរបុរាណប្រើសម្ភារៈអ្វីជាចម្បង?', '🛕', ['ថ្មភក់ និងឥដ្ឋ', 'ដែក និងបេតុង', 'ឈើតែមួយ', 'កញ្ចក់'], 0),
  ], 20, 'medium'),

  funQuiz('food', 'ម្ហូបអាហារពិភពលោក', 'Food Around the World', 'general', '🍜', [
    qi('Which country is famous for sushi?', '🍣', ['China', 'Japan', 'Korea', 'Vietnam'], 1),
    qi('"Amok" is a traditional dish from which country?', '🍲', ['Malaysia', 'Vietnam', 'Cambodia', 'Laos'], 2),
    qi('Pizza originated in which country?', '🍕', ['France', 'Italy', 'Greece', 'Spain'], 1),
    qi('Which spice is the most expensive by weight?', '🌶️', ['Saffron', 'Vanilla', 'Cardamom', 'Cinnamon'], 0),
    qi('"Pho" is a noodle soup from which country?', '🍜', ['Vietnam', 'Cambodia', 'Laos', 'China'], 0),
    qi('Which fruit is called the "king of fruits" in Southeast Asia?', '🍈', ['Mango', 'Durian', 'Jackfruit', 'Rambutan'], 1),
    qi('Kimchi is a fermented dish from which country?', '🥬', ['Japan', 'China', 'South Korea', 'Mongolia'], 2),
    qi('Which grain is the staple food of Cambodia?', '🍚', ['Wheat', 'Rice', 'Corn', 'Barley'], 1),
    qi('"Num banh chok" is a Cambodian dish made of what?', '🍜', ['Rice noodles with fish curry', 'Fried rice', 'Grilled beef', 'Sticky rice cake'], 0),
    qi('Which country is the origin of tacos?', '🌮', ['Spain', 'Mexico', 'Peru', 'Brazil'], 1),
    qi('Which nut is used to make traditional pesto?', '🌰', ['Almond', 'Pine nut', 'Walnut', 'Cashew'], 1),
    qi('"Prahok" is a Cambodian ingredient made from what?', '🐟', ['Fermented fish paste', 'Palm sugar', 'Coconut milk', 'Rice flour'], 0),
    qi('Which country invented the croissant\'s modern form?', '🥐', ['France', 'Austria', 'Italy', 'Belgium'], 0),
    qi('Which drink is made from fermented tea?', '🍵', ['Kombucha', 'Cider', 'Soda', 'Lassi'], 0),
    qi('Which spice gives curry its yellow colour?', '🍛', ['Paprika', 'Turmeric', 'Cumin', 'Coriander'], 1),
    qi('"Lok lak" is a Cambodian dish featuring which meat?', '🥩', ['Beef', 'Fish', 'Duck', 'Pork only'], 0),
    qi('Which country consumes the most rice per person?', '🍚', ['Bangladesh', 'United States', 'France', 'Germany'], 0),
    qi('Palm sugar in Cambodia is harvested from which tree?', '🌴', ['Sugar palm', 'Coconut palm', 'Banana tree', 'Mango tree'], 0),
  ], 15, 'easy'),

  funQuiz('tech', 'បច្ចេកវិទ្យា និងអ៊ីនធឺណិត', 'Tech & Internet', 'general', '💻', [
    qi('What does "HTTP" stand for?', '💻', ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'Hyperlink Text Transfer Process', 'Host Transfer Text Protocol'], 0),
    qi('Which company created Android?', '📱', ['Apple', 'Microsoft', 'Google', 'Samsung'], 2),
    qi('What does "WWW" stand for?', '🌐', ['World Wide Web', 'Web Wide World', 'Wide World Web', 'World Web Wide'], 0),
    qi('Which protocol keeps a persistent two-way connection open between browser and server?', '🔌', ['HTTP/1.1', 'WebSocket', 'FTP', 'SMTP'], 1),
    qi('What does "AI" stand for?', '🤖', ['Automatic Input', 'Artificial Intelligence', 'Advanced Internet', 'Applied Informatics'], 1),
    qi('Which language is used mainly for styling web pages?', '🎨', ['HTML', 'SQL', 'CSS', 'Python'], 2),
    qi('Who co-founded Microsoft with Paul Allen?', '💻', ['Steve Jobs', 'Larry Page', 'Jeff Bezos', 'Bill Gates'], 3),
    qi('What does "URL" stand for?', '🔗', ['Uniform Resource Locator', 'Universal Reference Link', 'User Registered Location', 'Unified Routing Layer'], 0),
    qi('What does "CPU" stand for?', '🖥️', ['Central Processing Unit', 'Computer Power Unit', 'Central Program Utility', 'Core Processing Underlay'], 0),
    qi('Which language is primarily used to structure a web page?', '📄', ['CSS', 'HTML', 'JavaScript', 'SQL'], 1),
    qi('What does "RAM" stand for?', '💾', ['Random Access Memory', 'Read Access Mode', 'Rapid Application Memory', 'Remote Access Module'], 0),
    qi('Which database language is used to query relational data?', '🗄️', ['SQL', 'HTML', 'CSS', 'XML'], 0),
    qi('What does a "load balancer" do?', '⚖️', ['Distributes traffic across servers', 'Stores files', 'Renders CSS', 'Compresses images'], 0),
    qi('Which company developed the React library?', '⚛️', ['Google', 'Meta (Facebook)', 'Microsoft', 'Amazon'], 1),
    qi('What does "VPN" stand for?', '🔒', ['Virtual Private Network', 'Verified Public Node', 'Variable Packet Number', 'Virtual Public Name'], 0),
    qi('Which port does HTTPS use by default?', '🔒', ['80', '443', '21', '25'], 1),
    qi('What does "open source" mean?', '🔓', ['The source code is publicly available', 'The software is always free of bugs', 'It only runs on Linux', 'It has no licence'], 0),
    qi('Which of these is a version control system?', '🌿', ['Git', 'Docker', 'Nginx', 'Redis'], 0),
  ], 18, 'medium'),

  funQuiz('space', 'អវកាស និងវិទ្យាសាស្ត្រ', 'Space & Science', 'general', '🚀', [
    qi('Which planet is known as the Red Planet?', '🔴', ['Venus', 'Mars', 'Jupiter', 'Mercury'], 1),
    qi('What is the closest star to Earth?', '☀️', ['The Sun', 'Proxima Centauri', 'Sirius', 'Alpha Centauri A'], 0),
    qi('Who was the first human in space?', '🚀', ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Alan Shepard'], 1),
    qi('How long does sunlight take to reach Earth?', '☀️', ['About 8 minutes', 'About 8 seconds', 'About 8 hours', 'About 8 days'], 0),
    qi('Which planet has the most confirmed moons?', '🪐', ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], 1),
    qi('Which is the largest planet in the Solar System?', '🪐', ['Saturn', 'Neptune', 'Jupiter', 'Earth'], 2),
    qi('Which gas do humans exhale as a waste product?', '💨', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], 2),
    qi('Which space telescope launched in December 2021?', '🔭', ['Hubble', 'Kepler', 'Spitzer', 'James Webb'], 3),
    qi('What is the hottest planet in the Solar System?', '🌡️', ['Mercury', 'Venus', 'Mars', 'Jupiter'], 1),
    qi('How many planets are in our Solar System?', '🪐', ['7', '8', '9', '10'], 1),
    qi('What force keeps planets in orbit around the Sun?', '🌍', ['Magnetism', 'Gravity', 'Friction', 'Electricity'], 1),
    qi('What is the chemical symbol for gold?', '🧪', ['Go', 'Gd', 'Au', 'Ag'], 2),
    qi('Which galaxy do we live in?', '🌌', ['Andromeda', 'Milky Way', 'Triangulum', 'Whirlpool'], 1),
    qi('What is the speed of light in a vacuum (approx.)?', '💡', ['300 km/s', '3,000 km/s', '300,000 km/s', '30,000 km/s'], 2),
    qi('Which organ pumps blood around the human body?', '❤️', ['Lungs', 'Heart', 'Liver', 'Kidney'], 1),
    qi('What is the most abundant gas in Earth\'s atmosphere?', '🌬️', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'], 1),
    qi('A "light year" measures what?', '✨', ['Distance', 'Time', 'Brightness', 'Mass'], 0),
    qi('Which country landed the first spacecraft on the far side of the Moon?', '🌑', ['United States', 'Russia', 'China', 'India'], 2),
  ], 18, 'hard'),
];
